server:
  port: 8085
  servlet:
    context-path: /blog
#  error:
#    include-message: never
#    whitelabel:
#      enabled: off
#
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method


spring:
  application.name: blog-service

#  config:
#    activate:
#      on-profile: dev

#  web:
#    resources:
#      chain:
#        cache: true
#        strategy:
#          content:
#            enabled: true
#      cache:
#        cachecontrol:
#          max-age: 7d

  datasource:
    url: jdbc:postgresql://localhost:5432/common-db
#    url: jdbc:postgresql://postgres-common:5432/common-db
    username: sa
    password: 12
    driver-class-name: org.postgresql.Driver

#  liquibase:
#    enabled: false
#    change-log: classpath:db/changelog/db.changelog-master.xml


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update

#  jackson:
#    deserialization:
#      FAIL_ON_IGNORED_PROPERTIES: false
#    serialization:
#      INDENT_OUTPUT: false
#      WRITE_DATES_AS_TIMESTAMPS: false
#      WRITE_BIGDECIMAL_AS_PLAIN: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/advanced-project-realm
#          issuer-uri: http://keycloak:8081/auth/realms/advanced-project-realm

#management:
#  health:
#    livenessState.enabled: true
#    readinessState.enabled: true
#  endpoint.health.probes.enabled: true

management:

  endpoints:
    web:
      exposure:
        include: health,prometheus

  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
#
#logging:
#  level:
#    org.springframework: DEBUG
