server:
  port: 8086



#spring.data.mongodb.uri=mongodb://localhost:27017/bezkoder_db

spring:
  application.name: profile-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/advanced-project-realm
#          issuer-uri: http://keycloak:8081/auth/realms/advanced-project-realm
