
#  auth:
#    image: quay.io/keycloak/keycloak:latest
#    ports:
#      - "8180:8180"
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: password
#
#      KC_DB: postgres
#      KC_DB_USERNAME: sa
#      KC_DB_PASSWORD: 12
#      KC_DB_URL: "jdbc:postgresql://common-service-postgres:5432/keycloak"
#
##      KEYCLOAK_IMPORT: /tmp/keycloak/config/realm-export.json
#      KC_IMPORT: /tmp/keycloak/config/realm-export.json
#
#    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev""]
##    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev", "--auto-build", "--import file /tmp/keycloak/config/realm-export.json"]
##    command:
##      - start-dev
##      - --http-port=8180
##      - --import-realm
#    volumes:
#      - ./service-cloud/keycloak-auth/config:/opt/keycloak/data/import
#      - ./service-cloud/keycloak-auth/config:/tmp/keycloak/config

auth3:
  image: quay.io/keycloak/keycloak:18.0
  ports:
    - "8080:8080"
  environment:
    KEYCLOAK_ADMIN: admin
    KEYCLOAK_ADMIN_PASSWORD: admin
    KC_DB: postgres
    KC_DB_USERNAME: sa
    KC_DB_PASSWORD: 12
    KC_DB_URL: "jdbc:postgresql://common-service-postgres:5432/keycloak"
  command:
    - start-dev
    - --import-realm
  volumes:
    - ./service-cloud/keycloak-auth/config/realm3.json:/opt/keycloak/data/import/realm.json



#  keycloak:
#    build:
#      context: service-cloud/keycloak-auth
#      dockerfile: Dockerfile2
#    environment:
#      DB_VENDOR: POSTGRES
#      DB_ADDR: keycloak-postgres
#      DB_DATABASE: keycloak
#      DB_USER: keycloak
#      DB_SCHEMA: public
#      DB_PASSWORD: password
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: password
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: password
#    ports:
#      - 8081:8081
#    depends_on:
#      - keycloak-postgres

#  keycloak-postgres:
#    image: postgres
#    volumes:
#      - keycloak-postgres_data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: keycloak
#      POSTGRES_USER: keycloak
#      POSTGRES_PASSWORD: password
#    ports:
#      - 5432:5432
