version: '3'

volumes:
  postgres_data:
    driver: local

services:

# В настройках реалма лежат коды доступа если что
  keycloak:
    image: quay.io/keycloak/keycloak:19.0
    container_name: keycloak
    environment:
#      KC_DB: mysql
#      KC_DB_URL: jdbc:mysql://cp-keycloak-database:3306/keycloak
#      KC_DB_USERNAME: root
#      KC_DB_PASSWORD: root
#      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8081:8081
    volumes:
      - ./conf:/opt/keycloak/conf
      - ./realms:/opt/keycloak/data/import/
      - ./themes:/opt/keycloak/themes
    entrypoint: "/opt/keycloak/bin/kc.sh start-dev --import-realm --features scripts --http-relative-path=/auth --http-port=8081"

#  postgres:
#    image: postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: keycloak
#      POSTGRES_USER: keycloak
#      POSTGRES_PASSWORD: password
#    ports:
#      - 5432:5432
